<?php
/* English */
$tooltips = array(
"pan" => "Pan the map",
"rectangle" => "Create a rectangle",
"ellipse" => "Create an ellipse",
"region" => "Create a polygon",
"path" => "Create a path",
"freeform" => "Freeform line",
"point" => "Create a point",
"move" => "Edit or move a landmark",
"measure" => "Measure",
"openMap" => "Go back to mapping home page to create and open maps",
"newMap" => "Create a new map",
"editMap" => "Edit map information",
"centerMap" => "Set this view to default map location",
"downloadImg" => "Download image",
"embed" => "Embed this map on your site",
"textnote" => "Create a new text note",
"moving" => "Done moving",
"search" => "Search",
"gosearch" => "Search",
"uploadImg" => "Upload an image",
"label" => "Label",
"color" => "Color",
"description" => "Description",
"audio" => "Create an audio recording",
"undo" => "Undo the last map change",
"make" => "Make",
"done" => "Done",
"deleteBtn" => "Delete",
"edit" => "Edit",
"cancel" => "Cancel",
"untitled" => "Untitled",
"enter_description" => "Enter a description here",
"perimeter" => "Perimeter",
"meters" => "Meters",
"lengthTxt" => "Length"
);
$instructions = array(
"path" => "Draw a path to outline a landmark. Click to add points to the path.",
"textnote" => "Click on the map to place a text note.",
"ellipse" => "Click on the map to place an ellipse.",
"rectangle" => "Click on the map to place a rectangle. The rectangle can be resized and dragged.",
"region" => "Draw an area to outline a landmark.",
"freeform" => "Hold the mouse down to begin drawing a freeform shape. Drag the mouse to outline your path. Release the mouse to stop drawing.",
"point" => "Click on the map to create a new point of interest.",
"search" => "Enter a search term.",
"uploadImg" => "Click on the map to place an image.",
"audio" => "Click on the map to place an audio recording."
);
?>
