<?php
/* Portuguese */
$tooltips = array(
"pan" => "Navegar no mapa",
"rectangle" => "Desenhar um retângulo",
"ellipse" => "Desenhar uma elipse",
"region" => "Desenhar um polígono",
"path" => "Desenhar um caminho",
"freeform" => "Fazer um desenho livre",
"point" => "Marcar um ponto",
"move" => "Editar ou mover um marco",
"measure" => "Fazer medições",
"openMap" => "Volte à página inicial do Cartagen para criar e abrir mapas",
"newMap" => "Criar um novo mapa",
"editMap" => "Editar informações sobre o mapa",
"centerMap" => "Marcar essa visualização como a padrão do mapa",
"downloadImg" => "Descarregar a imagem",
"embed" => "Incluir este mapa no seu site",
"textnote" => "Criar uma nova anotação",
"moving" => "Encerrar movimento",
"search" => "Buscar",
"gosearch" => "Buscar",
"uploadImg" => "Carregar uma imagem",
"label" => "Etiqueta",
"color" => "Cor",
"description" => "Descrição",
"audio" => "Criar uma gravação de áudio",
"undo" => "Desfazer última alteração do mapa",
"make" => "Make",
"done" => "Done",
"deleteBtn" => "Delete",
"edit" => "Edit",
"cancel" => "Cancel",
"untitled" => "Untitled",
"enter_description" => "Enter a description here",
"perimeter" => "Perimeter",
"meters" => "Meters",
"lengthTxt" => "Length"
);
$instructions = array(
"path" => "Desenhe um caminho no mapa. Clique para inserir novos pontos neste caminho.",
"textnote" => "Clique no mapa para inserir uma anotação.",
"ellipse" => "Clique no mapa para fazer uma elipse. A elipse pode ser redimensionada e arrastada.",
"rectangle" => "Clique no mapa para inserir um retângulo. O retângulo pode ser redimensionado e arrastado.",
"region" => "Clique no mapa para inserir um polígono.",
"freeform" => "Pressione o botão do mouse eo mantenha apertado para desenhar uma figura livre. :Solte o mouse para parar de desenhar.",
"point" => "Clique no mapa para inserir um novo ponto de interesse.",
"search" => "Enter a search term.",
"uploadImg" => "Click on the map to place an image.",
"audio" => "Clique no mapa para inserir uma gravação de áudio."
);
?>
